FROM mongo:8.0.13
# 8 représente la version majeure
# 0 représente la version mineure 
# 13 patch : représente les correctifs
# ce qu'il y a après représente les ref de compilations faites donc vaut mieux prendre une version avec des correctifs seulement  

ENV MONGO_INITDB_ROOT_USERNAME=hulya
ENV MONGO_INITDB_ROOT_PASSWORD=azerty